### ISSUE TITLE
End user confusion copying examples elsewhere

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/near-sdk-rs#96]
**Problem**:
As a user I don't fully understand how to write smart contracts in Rust. So I clone this repo and build the examples and am happy with them. I want to copy one of the example folders out of the cloned repo and into my Documents folder. I plan to modify the example and use it as a base. When I try `… cargo build` I get an error and am confused.

**Reason**:
The `Cargo.toml` file uses relative paths for the `near-bindgen` dependency.
`near-bindgen = { path = "../../near-bindgen"}`

**Solution**:
Change examples to use a version instead.
Example:
`near-bindgen = "^0.4"`

**Possible Downside**:
This may be another thing for `near-bindgen` core developers to remember.

**Comment by mikedotexe** [comment]
Looks like there are other paths necessary to build.
<img width="778" alt="Screenshot 2020-02-24 15 06 01" src="https://user-images.githubusercontent.com/1042667/75199193-431c1680-5717-11ea-8d0c-dcbfbc6ab635.png">
Perhaps this is a slightly bigger effort than I thought, but coming from my side as a DevX advocate, I believe users will experience extra hurdles with the relative paths we currently have.

**Comment by nearmax** [comment]
This contract demonstrates the factory example -- deploying one contract with another contract. To be able to deploy another contract it needs to know its location in the file system.

**Comment by nearmax** [comment]
We need to have a general discussion on whether we want Rust examples to be in one place or not.  @evgenykuzyakov and me think that we benefit from having Rust examples next to near-bindgen because then we can use it for CI.

We were planning to have a dedicated repository with all smart contract examples that would include full-stack dApps, and lots of bare contracts (like exchanges and tokens). The plan was to have a CI on near-bindgen repo that would pull these examples and try to test them using the commit in the PR of the near-bindgen, to make sure near-bindgen changes are not breaking examples. @janedegtiareva what is the status on that? 

Also CC @damons , @bowenwang1996, @ailisp  since it is a part of the release process.

**Comment by mikedotexe** [comment]
> We were planning to have a dedicated repository with all smart contract examples that would include full-stack dApps

Okay, I'd like that a lot. I am in the middle of writing a tutorial on Rust and wanting to make sure I _should_ send end users to those examples. I will make sure to explain that they're supposed to be run in that repo for now.

**Comment by evgenykuzyakov** [comment]
I think we can just use mixed dependency:
```toml
near-bindgen = { path = "../../near-bindgen", version = "0.4.2"}
```

**Comment by mikedotexe** [comment]
> I think we can just use mixed dependency:
> 
> ```toml
> near-bindgen = { path = "../../near-bindgen", version = "0.4.2"}
> ```

Yeah, I tried that before. Seems like that should work! But it doesn't.  sad 🐼
<img width="529" alt="Screenshot 2020-02-26 16 30 13" src="https://user-images.githubusercontent.com/1042667/75400883-59f86f80-58b5-11ea-8536-098692e52d32.png">

**Comment by mikedotexe** [comment]
Going to close this. DevX is moving all the relevant examples into standalone repos. This particular example lives here:
https://github.com/near-examples/rust-high-level-cross-contract
This issue about using relative paths for crates no longer is important, as we'll be using the repo just mentioned instead.
